name: emontx_sniffer
description:  read emontx 'jeelib' datas and send to emoncms
version: alpine3.21.2
image: rob570/emontx_sniffer
slug: emontx_sniffer
url: https://github.com/rob570/emontx_sniffer/discussions
init: true
homeassistant_api: true
uart: true
arch:
  - armv7
  - aarch64
  - amd64
options:
  MQTT_USER: emonpi
  MQTT_PASSWORD: emonpimqtt2016
  MQTT_TOPIC: emon
  PORT: /dev/ttyS0
  RFM69_CONF: 15i 200g
  VERBOSITY: true
schema:
  MQTT_USER: str
  MQTT_PASSWORD: str
  MQTT_TOPIC: str?
  MQTT_HOST: str?
  MQTT_PORT: int?
  RFM69_CONF: str?
  PORT: list(/dev/ttyAMA0|/dev/ttyUSB0|/dev/ttyS0)
  VERBOSITY: bool
