name: emontx_sniffer
description:  read emontx 'jeelib' datas and send to emoncms
version: alpine3.18
image: alexjunk/emontx_sniffer
slug: emontx_sniffer
url: https://github.com/Open-Building-Management/emontx_sniffer/discussions
init: true
homeassistant_api: true
uart: true
arch:
  - armv7
  - aarch64
  - amd64
options:
  MQTT_USER: emonpi
  MQTT_PASSWORD: emonpimqtt2016
  PORT: list("/dev/ttyAMA0", "/dev/ttyUSB0")
  VERBOSITY: false
schema:
  MQTT_USER: str
  MQTT_PASSWORD: str
  MQTT_HOST: str?
  MQTT_PORT: int?
  VERBOSITY: bool
